"use client";

import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type Tab = "overview"|"stock"|"engin"|"outillage"|"acces";
type Status = "disponible"|"affecte"|"maintenance"|"hors_service"|"restitue";
type Agency = { id:string; name:string; contact_name:string|null; phone:string|null; email:string|null; active:boolean };
type Location = { id:string; name:string };
type Person = { id:string; full_name:string };
type Asset = { id:string; category:"engin"|"outillage"|"acces"; access_type:"pirl"|"echafaudage"|null; internal_reference:string; rental_reference:string|null; rental_agency_id:string|null; brand:string|null; description:string; serial_number:string|null; rental_start_date:string|null; rental_planned_end_date:string|null; rental_actual_end_date:string|null; rental_contract_number:string|null; rental_cost:number|string|null; rental_cost_frequency:"jour"|"mois"|null; vic_date:string|null; vic_due_date:string|null; status:Status; stock_location_id:string|null; person_id:string|null; notes:string|null; active:boolean; rental_agencies:Agency|null; stock_locations:Location|null; people:Person|null };
type DocumentRow = { id:string; asset_id:string; document_type:string; file_name:string; storage_path:string; created_at:string };
const statusLabels:Record<Status,string>={disponible:"Disponible",affecte:"Affecté",maintenance:"En maintenance",hors_service:"Hors service",restitue:"Restitué"};
const categoryLabels={engin:"Engins",outillage:"Électroportatif / Outillage",acces:"Moyens d’accès"};
const documentLabels:Record<string,string>={contrat_location:"Contrat de location",rapport_vic:"Rapport VIC",rapport_verification:"Rapport de vérification",photo:"Photo",autre:"Autre"};
const daysUntil=(date:string|null)=>date?Math.ceil((new Date(`${date}T12:00:00`).getTime()-Date.now())/86400000):null;

export function MagasinManager({section:tab,accessToken,toast}:{section:Tab;accessToken:string;toast:(message:string)=>void}){
  const [assets,setAssets]=useState<Asset[]>([]),[agencies,setAgencies]=useState<Agency[]>([]),[locations,setLocations]=useState<Location[]>([]),[people,setPeople]=useState<Person[]>([]),[documents,setDocuments]=useState<DocumentRow[]>([]);
  const [projectId,setProjectId]=useState(""),[warningDays,setWarningDays]=useState(30),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("all"),[selected,setSelected]=useState<Asset|null>(null),[showAsset,setShowAsset]=useState(false),[showAgency,setShowAgency]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function load(){const db=createSupabaseBrowserClient();const {data:project}=await db.from("projects").select("id,vic_warning_days").eq("code","24-018").single();if(!project)return;const [a,b,c,d,e]=await Promise.all([db.from("equipment_assets").select("*,rental_agencies(id,name,contact_name,phone,email,active),stock_locations(id,name),people(id,full_name)").eq("project_id",project.id).order("description"),db.from("rental_agencies").select("*").eq("project_id",project.id).order("name"),db.from("stock_locations").select("id,name").eq("project_id",project.id).eq("active",true).order("name"),db.from("people").select("id,full_name").eq("project_id",project.id).eq("active",true).order("full_name"),db.from("equipment_documents").select("id,asset_id,document_type,file_name,storage_path,created_at").eq("project_id",project.id).order("created_at",{ascending:false})]);setProjectId(project.id);setWarningDays(Number(project.vic_warning_days||30));setAssets((a.data||[]) as unknown as Asset[]);setAgencies((b.data||[]) as Agency[]);setLocations((c.data||[]) as Location[]);setPeople((d.data||[]) as Person[]);setDocuments((e.data||[]) as DocumentRow[])}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
  async function send(body:Record<string,unknown>){const response=await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${accessToken}`},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Enregistrement impossible");return result}
  const filtered=assets.filter(asset=>(tab==="overview"||tab==="stock"||asset.category===tab)&&(`${asset.internal_reference} ${asset.brand||""} ${asset.description}`.toLowerCase().includes(query.toLowerCase()))&&(statusFilter==="all"||asset.status===statusFilter));
  async function assetSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const f=new FormData(event.currentTarget);try{await send({kind:selected?"equipment-update":"equipment-create",assetId:selected?.id,category:f.get("category"),accessType:f.get("accessType")||null,internalReference:f.get("internalReference"),rentalReference:f.get("rentalReference"),rentalAgencyId:f.get("rentalAgencyId")||null,brand:f.get("brand"),description:f.get("description"),serialNumber:f.get("serialNumber"),rentalStartDate:f.get("rentalStartDate")||null,rentalPlannedEndDate:f.get("rentalPlannedEndDate")||null,rentalActualEndDate:f.get("rentalActualEndDate")||null,rentalContractNumber:f.get("rentalContractNumber"),rentalCost:f.get("rentalCost")?Number(f.get("rentalCost")):null,rentalCostFrequency:f.get("rentalCostFrequency")||null,vicDate:f.get("vicDate")||null,vicDueDate:f.get("vicDueDate")||null,status:f.get("status"),stockLocationId:f.get("stockLocationId")||null,personId:f.get("personId")||null,notes:f.get("notes"),active:f.get("active")==="on"});toast(selected?"Matériel mis à jour":"Matériel ajouté");setShowAsset(false);setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}}
  async function agencySubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const f=new FormData(event.currentTarget);try{await send({kind:"rental-agency-create",name:f.get("name"),contactName:f.get("contactName"),phone:f.get("phone"),email:f.get("email")});toast("Agence de location ajoutée");setShowAgency(false);await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}}
  async function toggleAgency(agency:Agency){try{await send({kind:"rental-agency-active",agencyId:agency.id,active:!agency.active});toast(agency.active?"Agence désactivée":"Agence réactivée");await load()}catch(e){toast(e instanceof Error?e.message:"Erreur")}}
  async function quickMove(asset:Asset,type:string){try{await send({kind:"equipment-movement",assetId:asset.id,movementType:type,personId:type==="affectation"?asset.person_id:null,stockLocationId:asset.stock_location_id,note:type==="maintenance"?"Mise en maintenance depuis le registre":null});toast("Statut du matériel mis à jour");await load()}catch(e){toast(e instanceof Error?e.message:"Erreur")}}
  async function uploadDocument(event:React.ChangeEvent<HTMLInputElement>,asset:Asset){const file=event.target.files?.[0];if(!file)return;const type=event.target.dataset.documentType||"autre";setSaving(true);try{const db=createSupabaseBrowserClient();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${projectId}/${asset.id}/${file.lastModified}-${safe}`;const {error:uploadError}=await db.storage.from("equipment-documents").upload(path,file);if(uploadError)throw uploadError;await send({kind:"equipment-document",assetId:asset.id,documentType:type,fileName:file.name,storagePath:path});toast("Document ajouté");await load()}catch(e){toast(e instanceof Error?e.message:"Envoi impossible")}finally{setSaving(false);event.target.value=""}}
  async function openDocument(document:DocumentRow){const db=createSupabaseBrowserClient();const {data,error:downloadError}=await db.storage.from("equipment-documents").createSignedUrl(document.storage_path,300);if(downloadError||!data){toast("Document inaccessible");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
  return <div className="content page-content magasin-page"><div className="page-head"><div><h2>{categoryLabels[tab as keyof typeof categoryLabels]}</h2><p>{tab==="engin"?"Locations, VIC et disponibilité des engins.":tab==="outillage"?"Suivi individuel, affectations et état de l’outillage.":"PIRL, échafaudages et échéances de vérification."}</p></div><div className="stock-actions">{tab==="engin"?<button onClick={()=>setShowAgency(true)}>＋ Agence de location</button>:null}<button className="primary" onClick={()=>{setSelected(null);setShowAsset(true)}}>＋ Ajouter</button></div></div>
    {<><div className="filters magasin-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher par référence, marque ou description…"/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Tous les statuts</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><div className="panel magasin-table"><table><thead><tr><th>RÉFÉRENCE</th><th>MATÉRIEL</th><th>LOCATION / AFFECTATION</th><th>VIC</th><th>STATUT</th><th></th></tr></thead><tbody>{filtered.map(asset=>{const due=daysUntil(asset.vic_due_date);return <tr key={asset.id}><td><b>{asset.internal_reference}</b><small>{asset.rental_reference||"—"}</small></td><td><b>{asset.description}</b><small>{[asset.brand,asset.serial_number,asset.access_type?.toUpperCase()].filter(Boolean).join(" · ")||"—"}</small></td><td>{asset.rental_agencies?.name||asset.people?.full_name||asset.stock_locations?.name||"—"}</td><td><span className={due!==null&&due<0?"equipment-overdue":due!==null&&due<=warningDays?"equipment-warning":""}>{asset.vic_due_date?new Date(`${asset.vic_due_date}T12:00:00`).toLocaleDateString("fr-FR"):"—"}</span></td><td><span className={`equipment-status ${asset.status}`}>{statusLabels[asset.status]}</span></td><td><button onClick={()=>{setSelected(asset);setShowAsset(true)}}>Gérer</button></td></tr>})}</tbody></table></div></>}
    {showAsset&&<div className="modal-backdrop"><form className="task-modal equipment-modal equipment-modal-simple" onSubmit={assetSubmit}>
      <div className="modal-title"><div><span>{tab==="engin"?"ENGIN":tab==="outillage"?"OUTILLAGE":"MOYEN D’ACCÈS"}</span><h3>{selected?"Modifier":"Ajouter"} {tab==="engin"?"un engin":tab==="outillage"?"un équipement":"un moyen d’accès"}</h3></div><button type="button" onClick={()=>{setShowAsset(false);setSelected(null)}}>×</button></div>
      <input type="hidden" name="category" value={tab}/>
      <div className="equipment-form-grid simple">
        <label>Référence interne<input name="internalReference" required defaultValue={selected?.internal_reference}/></label>
        <label className="span-2">Description<input name="description" required defaultValue={selected?.description}/></label>
        {tab==="engin"?<><label>Référence agence<input name="rentalReference" defaultValue={selected?.rental_reference||""}/></label><label>Agence de location<select name="rentalAgencyId" defaultValue={selected?.rental_agency_id||""}><option value="">Sélectionner…</option>{agencies.filter(a=>a.active).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>N° de contrat<input name="rentalContractNumber" defaultValue={selected?.rental_contract_number||""}/></label><label>Début de location<input type="date" name="rentalStartDate" defaultValue={selected?.rental_start_date||""}/></label><label>Fin prévisionnelle<input type="date" name="rentalPlannedEndDate" defaultValue={selected?.rental_planned_end_date||""}/></label><label>Fin réelle<input type="date" name="rentalActualEndDate" defaultValue={selected?.rental_actual_end_date||""}/></label><label>Coût de location<input type="number" min="0" step="0.01" name="rentalCost" defaultValue={selected?.rental_cost===null?"":Number(selected?.rental_cost||"")}/></label><label>Facturation<select name="rentalCostFrequency" defaultValue={selected?.rental_cost_frequency||""}><option value="">—</option><option value="jour">Par jour</option><option value="mois">Par mois</option></select></label><label>Date de VIC<input type="date" name="vicDate" defaultValue={selected?.vic_date||""}/></label><label>Échéance VIC<input type="date" name="vicDueDate" defaultValue={selected?.vic_due_date||""}/></label></>:null}
        {tab==="outillage"?<><label>Marque<input name="brand" defaultValue={selected?.brand||""}/></label><label>N° de série<input name="serialNumber" defaultValue={selected?.serial_number||""}/></label><label>Emplacement<select name="stockLocationId" defaultValue={selected?.stock_location_id||""}><option value="">Sélectionner…</option>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Responsable<select name="personId" defaultValue={selected?.person_id||""}><option value="">Non affecté</option>{people.map(x=><option value={x.id} key={x.id}>{x.full_name}</option>)}</select></label></>:null}
        {tab==="acces"?<><label>Type<select name="accessType" required defaultValue={selected?.access_type||"pirl"}><option value="pirl">PIRL</option><option value="echafaudage">Échafaudage</option></select></label><label>Marque / modèle<input name="brand" defaultValue={selected?.brand||""}/></label><label>N° de série<input name="serialNumber" defaultValue={selected?.serial_number||""}/></label><label>Emplacement<select name="stockLocationId" defaultValue={selected?.stock_location_id||""}><option value="">Sélectionner…</option>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Dernière vérification<input type="date" name="vicDate" defaultValue={selected?.vic_date||""}/></label><label>Prochaine vérification<input type="date" name="vicDueDate" defaultValue={selected?.vic_due_date||""}/></label></>:null}
        <label>Statut<select name="status" defaultValue={selected?.status||"disponible"}>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
        <label className="span-2">Note<textarea name="notes" defaultValue={selected?.notes||""}/></label>
        <label className="stock-active-check"><input type="checkbox" name="active" defaultChecked={selected?.active??true}/> Actif</label>
      </div>
      {selected?<><div className="equipment-quick-actions">{tab==="outillage"?<><button type="button" onClick={()=>void quickMove(selected,"affectation")}>Affecter</button><button type="button" onClick={()=>void quickMove(selected,"retour")}>Retour</button></>:null}<button type="button" onClick={()=>void quickMove(selected,"maintenance")}>Maintenance</button><button type="button" onClick={()=>void quickMove(selected,"remise_service")}>Remettre en service</button>{tab==="engin"?<button type="button" onClick={()=>void quickMove(selected,"restitution")}>Restituer</button>:null}</div><div className="equipment-documents"><h4>Documents</h4><div className="document-upload-row">{Object.entries(documentLabels).map(([value,label])=><label key={value}>{label}<input type="file" accept=".pdf,image/png,image/jpeg" data-document-type={value} disabled={saving} onChange={e=>void uploadDocument(e,selected)}/></label>)}</div>{documents.filter(d=>d.asset_id===selected.id).map(document=><button type="button" key={document.id} onClick={()=>void openDocument(document)}>▤ {documentLabels[document.document_type]} · {document.file_name}</button>)}</div></>:null}
      {error?<div className="settings-error">{error}</div>:null}<div className="modal-actions"><button type="button" onClick={()=>{setShowAsset(false);setSelected(null)}}>Annuler</button><button className="primary" disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</button></div>
    </form></div>}
    {showAgency&&<div className="modal-backdrop"><form className="task-modal" onSubmit={agencySubmit}><div className="modal-title"><div><span>LOUEURS</span><h3>Agences de location</h3></div><button type="button" onClick={()=>setShowAgency(false)}>×</button></div>{agencies.length?<div className="rental-agency-list">{agencies.map(agency=><div key={agency.id}><span><b>{agency.name}</b><small>{[agency.contact_name,agency.phone,agency.email].filter(Boolean).join(" · ")||"Aucun contact"}</small></span><button type="button" onClick={()=>void toggleAgency(agency)}>{agency.active?"Désactiver":"Réactiver"}</button></div>)}</div>:null}<h4>Ajouter une agence</h4><label>Nom<input name="name" required/></label><label>Contact<input name="contactName"/></label><label>Téléphone<input name="phone"/></label><label>E-mail<input name="email" type="email"/></label>{error?<div className="settings-error">{error}</div>:null}<div className="modal-actions"><button type="button" onClick={()=>setShowAgency(false)}>Fermer</button><button className="primary" disabled={saving}>Ajouter</button></div></form></div>}
  </div>
}
