"use client";

import { useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

const families = ["Câble", "Cheminements", "Luminaires", "Supportage", "Boulonnerie", "Colliers", "Galva"];
const units = ["u", "m", "ml", "kg", "l", "boîte", "paquet"];
type Item = { id: string; reference: string; name: string; category: string; unit: string; minimum_quantity: number | string };
type Movement = { id: string; stock_item_id: string; movement_type: "entree" | "sortie"; quantity: number | string; person_id: string | null; zone_id: string | null; storage_zone: string | null; note: string | null; created_at: string; stock_items: { reference: string; name: string; unit: string } | null; people: { full_name: string } | null; zones: { name: string } | null };
type Person = { id: string; full_name: string };
type Zone = { id: string; name: string };

export function StockManager({ accessToken, toast }: { accessToken: string; toast: (message: string) => void }) {
  const [items, setItems] = useState<Item[]>([]); const [movements, setMovements] = useState<Movement[]>([]); const [people, setPeople] = useState<Person[]>([]); const [zones, setZones] = useState<Zone[]>([]);
  const [mode, setMode] = useState<"entree" | "sortie">("sortie"); const [selectedId, setSelectedId] = useState(""); const [family, setFamily] = useState("all"); const [stateFilter, setStateFilter] = useState("all"); const [query, setQuery] = useState("");
  const [quantity, setQuantity] = useState("1"); const [personId, setPersonId] = useState(""); const [zoneId, setZoneId] = useState(""); const [storageZone, setStorageZone] = useState("Magasin principal"); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); const [showNewItem, setShowNewItem] = useState(false); const [error, setError] = useState("");
  async function load() { const db = createSupabaseBrowserClient(); const { data: project } = await db.from("projects").select("id").eq("code", "24-018").single(); if (!project) return; const [itemResult, movementResult, peopleResult, zoneResult] = await Promise.all([db.from("stock_items").select("id,reference,name,category,unit,minimum_quantity").eq("project_id", project.id).order("name"), db.from("stock_movements").select("id,stock_item_id,movement_type,quantity,person_id,zone_id,storage_zone,note,created_at,stock_items(reference,name,unit),people(full_name),zones(name)").eq("project_id", project.id).order("created_at", { ascending: false }).limit(100), db.from("people").select("id,full_name").eq("project_id", project.id).eq("active", true).order("full_name"), db.from("zones").select("id,name").eq("project_id", project.id).order("name")]); const loadedItems = (itemResult.data || []) as Item[]; setItems(loadedItems); setMovements((movementResult.data || []) as unknown as Movement[]); setPeople((peopleResult.data || []) as Person[]); setZones((zoneResult.data || []) as Zone[]); setSelectedId((current) => loadedItems.some((item) => item.id === current) ? current : loadedItems[0]?.id || ""); setPersonId((current) => peopleResult.data?.some((person) => person.id === current) ? current : peopleResult.data?.[0]?.id || ""); setZoneId((current) => zoneResult.data?.some((zone) => zone.id === current) ? current : zoneResult.data?.[0]?.id || ""); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const balances = useMemo(() => { const result: Record<string, number> = {}; for (const movement of movements) result[movement.stock_item_id] = (result[movement.stock_item_id] || 0) + (movement.movement_type === "entree" ? Number(movement.quantity) : -Number(movement.quantity)); return result; }, [movements]);
  const filteredItems = items.filter((item) => { const stock = balances[item.id] || 0; const matchesQuery = `${item.reference} ${item.name}`.toLowerCase().includes(query.toLowerCase()); const matchesFamily = family === "all" || item.category === family; const matchesState = stateFilter === "all" || (stateFilter === "alert" ? stock <= Number(item.minimum_quantity) : stock > Number(item.minimum_quantity)); return matchesQuery && matchesFamily && matchesState; });
  const selected = items.find((item) => item.id === selectedId); const currentStock = selected ? balances[selected.id] || 0 : 0; const negativeAfterMovement = mode === "sortie" && Number(quantity) > currentStock;
  async function send(body: Record<string, unknown>) { const response = await fetch("/api/operations", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${accessToken}` }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Enregistrement impossible"); return result; }
  async function saveMovement() { if (!selected || !Number(quantity)) return; setSaving(true); setError(""); try { await send({ kind: "stock", movementType: mode, stockItemId: selected.id, quantity: Number(quantity), personId: mode === "sortie" ? personId : null, zoneId: mode === "sortie" ? zoneId : null, storageZone: mode === "entree" ? storageZone : null, note }); toast(`${mode === "entree" ? "Entrée" : "Sortie"} enregistrée`); setQuantity("1"); setNote(""); await load(); } catch (event) { setError(event instanceof Error ? event.message : "Erreur"); } finally { setSaving(false); } }
  async function createItem(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); try { const result = await send({ kind: "stock-item-create", reference: form.get("reference"), name: form.get("name"), category: form.get("category"), unit: form.get("unit"), minimumQuantity: Number(form.get("minimumQuantity")) }); toast("Article ajouté au catalogue"); setShowNewItem(false); await load(); if (result.item?.id) setSelectedId(result.item.id); } catch (event) { setError(event instanceof Error ? event.message : "Erreur"); } finally { setSaving(false); } }
  const alerts = items.filter((item) => (balances[item.id] || 0) <= Number(item.minimum_quantity)).length; const today = new Date().toLocaleDateString("en-CA"); const todayMovements = movements.filter((movement) => movement.created_at.slice(0, 10) === today).length;
  return <div className="content page-content"><div className="page-head"><div><h2>Suivi de stock</h2><p>Entrées, sorties et disponibilité réelle du matériel du chantier.</p></div><div className="stock-actions"><button onClick={() => setMode("entree")}>↓ Enregistrer une entrée</button><button className="primary" onClick={() => setMode("sortie")}>↑ Enregistrer une sortie</button></div></div>
    <div className="stock-kpis functional-stock-kpis"><div className="kpi green"><span>ARTICLES SUIVIS</span><b>{items.length}</b><small>{new Set(items.map((item) => item.category)).size} familles utilisées</small></div><div className="kpi red"><span>ALERTES STOCK</span><b>{alerts}</b><small>au seuil minimum ou en négatif</small></div><div className="kpi gold"><span>MOUVEMENTS DU JOUR</span><b>{todayMovements}</b><small>entrées et sorties enregistrées</small></div></div>
    <div className="stock-layout"><div className="panel stock-table"><div className="panel-title"><div><span>ÉTAT DU STOCK</span><h3>Matériel disponible</h3></div></div><div className="filters stock-filters"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="⌕  Rechercher un article…"/><select value={family} onChange={(event) => setFamily(event.target.value)}><option value="all">Toutes les familles</option>{families.map((value) => <option key={value}>{value}</option>)}</select><select value={stateFilter} onChange={(event) => setStateFilter(event.target.value)}><option value="all">Tous les états</option><option value="available">Disponible</option><option value="alert">Alerte stock</option></select></div><div className="stock-table-scroll"><table><thead><tr><th>ARTICLE</th><th>FAMILLE</th><th>DISPONIBLE</th><th>SEUIL</th><th>ÉTAT</th></tr></thead><tbody>{filteredItems.map((item) => { const stock = balances[item.id] || 0; const alert = stock <= Number(item.minimum_quantity); return <tr key={item.id} onClick={() => setSelectedId(item.id)} className={selectedId === item.id ? "stock-selected" : ""}><td><b>{item.name}</b><small>{item.reference}</small></td><td>{item.category}</td><td><strong>{stock.toLocaleString("fr-FR")} {item.unit}</strong></td><td>{Number(item.minimum_quantity).toLocaleString("fr-FR")} {item.unit}</td><td><span className={alert ? "stock-alert" : "stock-ok"}>● {stock < 0 ? "Stock négatif" : alert ? "Seuil atteint" : "Disponible"}</span></td></tr>; })}</tbody></table></div></div>
      <div className="panel movement-form"><div className="movement-tabs"><button className={mode === "sortie" ? "active" : ""} onClick={() => setMode("sortie")}>↑ Sortie</button><button className={mode === "entree" ? "active" : ""} onClick={() => setMode("entree")}>↓ Entrée</button></div><div className="movement-body"><span>NOUVEAU MOUVEMENT</span><h3>{mode === "sortie" ? "Sortie de matériel" : "Entrée en stock"}</h3><label>Article<select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{items.map((item) => <option value={item.id} key={item.id}>{item.reference} · {item.name}</option>)}</select></label>{mode === "entree" && <button className="text-action add-stock-item" onClick={() => setShowNewItem(true)}>＋ L’article n’existe pas ? L’ajouter</button>}<div className="available">Stock actuel <b>{currentStock.toLocaleString("fr-FR")} {selected?.unit || ""}</b></div><label>Quantité<input type="number" min="0.01" step="0.01" value={quantity} onChange={(event) => setQuantity(event.target.value)}/><small>{selected?.unit}</small></label>{mode === "sortie" ? <><label>Personne<select value={personId} onChange={(event) => setPersonId(event.target.value)}>{people.map((person) => <option value={person.id} key={person.id}>{person.full_name}</option>)}</select></label><label>Zone d’affectation<select value={zoneId} onChange={(event) => setZoneId(event.target.value)}>{zones.map((zone) => <option value={zone.id} key={zone.id}>{zone.name}</option>)}</select></label></> : <label>Zone de stockage<input value={storageZone} onChange={(event) => setStorageZone(event.target.value)} required/></label>}<label>Référence / commentaire<input value={note} onChange={(event) => setNote(event.target.value)} required={negativeAfterMovement} placeholder={negativeAfterMovement ? "Justification obligatoire du stock négatif" : mode === "sortie" ? "Bon de sortie, précision…" : "BL fournisseur, précision…"}/></label>{negativeAfterMovement && <div className="stock-negative-warning">⚠ Cette sortie créera un stock négatif. Ajoutez une justification.</div>}{error && <div className="settings-error">{error}</div>}<button className="save" disabled={saving || !selected || negativeAfterMovement && !note.trim()} onClick={() => void saveMovement()}>{saving ? "Enregistrement…" : "Valider le mouvement"}</button></div></div></div>
    <div className="panel movement-history"><div className="panel-title"><div><span>JOURNAL DES MOUVEMENTS</span><h3>Dernières opérations</h3></div></div><table><thead><tr><th>DATE</th><th>TYPE</th><th>ARTICLE</th><th>QUANTITÉ</th><th>AFFECTATION / STOCKAGE</th><th>COMMENTAIRE</th></tr></thead><tbody>{movements.map((movement) => <tr key={movement.id}><td>{new Date(movement.created_at).toLocaleString("fr-FR", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" })}</td><td><span className={movement.movement_type === "entree" ? "move-in" : "move-out"}>{movement.movement_type === "entree" ? "↓ Entrée" : "↑ Sortie"}</span></td><td><b>{movement.stock_items?.name}</b><small>{movement.stock_items?.reference}</small></td><td><strong>{movement.movement_type === "entree" ? "+" : "−"}{Number(movement.quantity).toLocaleString("fr-FR")} {movement.stock_items?.unit}</strong></td><td>{movement.movement_type === "entree" ? movement.storage_zone : [movement.people?.full_name, movement.zones?.name].filter(Boolean).join(" · ")}</td><td>{movement.note || "—"}</td></tr>)}</tbody></table></div>
    {showNewItem && <div className="modal-backdrop"><form className="task-modal" onSubmit={createItem}><div className="modal-title"><div><span>NOUVEL ARTICLE</span><h3>Ajouter au catalogue du chantier</h3></div><button type="button" onClick={() => setShowNewItem(false)}>×</button></div><label>Référence<input name="reference" required placeholder="Ex. CAB-4G2.5"/></label><label>Désignation<input name="name" required placeholder="Ex. Câble U1000 R2V 4G2,5"/></label><label>Famille<select name="category" required>{families.map((value) => <option key={value}>{value}</option>)}</select></label><label>Unité<select name="unit" required>{units.map((value) => <option key={value}>{value}</option>)}</select></label><label>Seuil d’alerte<input name="minimumQuantity" type="number" min="0" step="0.01" defaultValue="0" required/></label>{error && <div className="settings-error">{error}</div>}<div className="modal-actions"><button type="button" onClick={() => setShowNewItem(false)}>Annuler</button><button className="primary" disabled={saving}>{saving ? "Ajout…" : "Ajouter l’article"}</button></div></form></div>}
  </div>;
}
