"use client";

import { useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

const families = ["Câble", "Cheminements", "Luminaires", "Supportage", "Boulonnerie", "Colliers", "Galva"];
const units = ["u", "m", "ml", "kg", "l", "boîte", "paquet"];
type Mode = "entree" | "sortie" | "transfert" | "inventaire";
type Item = { id:string; reference:string; name:string; category:string; unit:string; minimum_quantity:number|string; active:boolean };
type Location = { id:string; name:string; code:string|null; active:boolean };
type Movement = { id:string; stock_item_id:string; movement_type:Mode; quantity:number|string; source_location_id:string|null; destination_location_id:string|null; inventory_delta:number|string|null; counted_quantity:number|string|null; previous_quantity:number|string|null; person_id:string|null; zone_id:string|null; note:string|null; created_at:string; stock_items:{reference:string;name:string;unit:string}|null; people:{full_name:string}|null; zones:{name:string}|null };
type Person = { id:string; full_name:string }; type Zone = { id:string; name:string };
type Tool = { id:string; internal_reference:string; description:string; brand:string|null; status:string; stock_location_id:string|null; person_id:string|null; active:boolean; stock_locations:{name:string}|null; people:{full_name:string}|null };
type ToolMovement = { id:string; asset_id:string; movement_type:string; stock_location_id:string|null; person_id:string|null; zone_id:string|null; note:string|null; created_at:string; equipment_assets:{internal_reference:string;description:string}|null; stock_locations:{name:string}|null; people:{full_name:string}|null; zones:{name:string}|null };

function signedQuantity(movement: Movement) { return movement.movement_type === "entree" ? Number(movement.quantity) : movement.movement_type === "sortie" ? -Number(movement.quantity) : movement.movement_type === "inventaire" ? Number(movement.inventory_delta || 0) : 0; }
function movementLabel(type: Mode) { return type === "entree" ? "↓ Entrée" : type === "sortie" ? "↑ Sortie" : type === "transfert" ? "⇄ Transfert" : "≡ Inventaire"; }

export function StockManager({ accessToken, toast }: { accessToken:string; toast:(message:string)=>void }) {
  const [items,setItems]=useState<Item[]>([]), [locations,setLocations]=useState<Location[]>([]), [movements,setMovements]=useState<Movement[]>([]), [people,setPeople]=useState<Person[]>([]), [zones,setZones]=useState<Zone[]>([]), [tools,setTools]=useState<Tool[]>([]), [toolMovements,setToolMovements]=useState<ToolMovement[]>([]);
  const [mode,setMode]=useState<Mode>("sortie"), [selectedId,setSelectedId]=useState(""), [family,setFamily]=useState("all"), [stateFilter,setStateFilter]=useState("active"), [query,setQuery]=useState("");
  const [operationKind,setOperationKind]=useState<"article"|"outillage">("article"),[selectedToolId,setSelectedToolId]=useState("");
  const [quantity,setQuantity]=useState("1"), [sourceId,setSourceId]=useState(""), [destinationId,setDestinationId]=useState(""), [personId,setPersonId]=useState(""), [zoneId,setZoneId]=useState(""), [note,setNote]=useState("");
  const [saving,setSaving]=useState(false), [showNewItem,setShowNewItem]=useState(false), [showEditItem,setShowEditItem]=useState(false), [showNewLocation,setShowNewLocation]=useState(false), [showDetail,setShowDetail]=useState(false), [error,setError]=useState("");
  async function load(){ const db=createSupabaseBrowserClient(); const {data:project}=await db.from("projects").select("id").eq("code","24-018").single(); if(!project)return; const [a,b,c,d,e,f,g]=await Promise.all([db.from("stock_items").select("id,reference,name,category,unit,minimum_quantity,active").eq("project_id",project.id).order("name"),db.from("stock_locations").select("id,name,code,active").eq("project_id",project.id).order("name"),db.from("stock_movements").select("id,stock_item_id,movement_type,quantity,source_location_id,destination_location_id,inventory_delta,counted_quantity,previous_quantity,person_id,zone_id,note,created_at,stock_items(reference,name,unit),people(full_name),zones(name)").eq("project_id",project.id).order("created_at",{ascending:false}).limit(1000),db.from("people").select("id,full_name").eq("project_id",project.id).eq("active",true).order("full_name"),db.from("zones").select("id,name").eq("project_id",project.id).order("name"),db.from("equipment_assets").select("id,internal_reference,description,brand,status,stock_location_id,person_id,active,stock_locations(name),people(full_name)").eq("project_id",project.id).eq("category","outillage").order("description"),db.from("equipment_movements").select("id,asset_id,movement_type,stock_location_id,person_id,zone_id,note,created_at,equipment_assets!inner(internal_reference,description,category),stock_locations(name),people(full_name),zones(name)").eq("project_id",project.id).eq("equipment_assets.category","outillage").order("created_at",{ascending:false}).limit(500)]); const loaded=(a.data||[]) as Item[], locs=(b.data||[]) as Location[],loadedTools=(f.data||[]) as unknown as Tool[]; setItems(loaded);setLocations(locs);setMovements((c.data||[]) as unknown as Movement[]);setPeople((d.data||[]) as Person[]);setZones((e.data||[]) as Zone[]);setTools(loadedTools);setToolMovements((g.data||[]) as unknown as ToolMovement[]);setSelectedId(v=>loaded.some(x=>x.id===v)?v:loaded.find(x=>x.active)?.id||"");setSelectedToolId(v=>loadedTools.some(x=>x.id===v)?v:loadedTools.find(x=>x.active)?.id||"");setSourceId(v=>locs.some(x=>x.id===v&&x.active)?v:locs.find(x=>x.active)?.id||"");setDestinationId(v=>locs.some(x=>x.id===v&&x.active)?v:locs.find(x=>x.active)?.id||"");setPersonId(v=>d.data?.some(x=>x.id===v)?v:d.data?.[0]?.id||"");setZoneId(v=>e.data?.some(x=>x.id===v)?v:e.data?.[0]?.id||""); }
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
  const locationBalances=useMemo(()=>{const out:Record<string,Record<string,number>>={};const add=(item:string,location:string|null,value:number)=>{if(!location)return;(out[item]??={})[location]=(out[item][location]||0)+value};for(const m of movements){if(m.movement_type==="entree")add(m.stock_item_id,m.destination_location_id,Number(m.quantity));else if(m.movement_type==="sortie")add(m.stock_item_id,m.source_location_id,-Number(m.quantity));else if(m.movement_type==="transfert"){add(m.stock_item_id,m.source_location_id,-Number(m.quantity));add(m.stock_item_id,m.destination_location_id,Number(m.quantity))}else add(m.stock_item_id,m.source_location_id,Number(m.inventory_delta||0))}return out},[movements]);
  const balances=useMemo(()=>Object.fromEntries(items.map(item=>[item.id,Object.values(locationBalances[item.id]||{}).reduce((a,b)=>a+b,0)])),[items,locationBalances]);
  const availableFamilies=useMemo(()=>Array.from(new Set(items.map(item=>item.category).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"fr")),[items]);
  const filteredItems=items.filter(item=>{const stock=balances[item.id]||0;return `${item.reference} ${item.name}`.toLowerCase().includes(query.toLowerCase())&&(family==="all"||item.category===family)&&(stateFilter==="all"||(stateFilter==="active"?item.active:stateFilter==="inactive"?!item.active:stock<=Number(item.minimum_quantity)))});
  const selected=items.find(x=>x.id===selectedId), currentStock=selected?balances[selected.id]||0:0, sourceStock=selected?locationBalances[selected.id]?.[sourceId]||0:0;
  const eligibleTools=tools.filter(tool=>tool.active&&(mode==="entree"?tool.status==="affecte":tool.status==="disponible"));
  const negative=mode==="sortie"&&Number(quantity)>sourceStock;
  useEffect(()=>{if(operationKind!=="outillage")return;setSelectedToolId(current=>eligibleTools.some(tool=>tool.id===current)?current:eligibleTools[0]?.id||"")},[operationKind,mode,tools]);
  async function send(body:Record<string,unknown>){const response=await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${accessToken}`},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Enregistrement impossible");return result}
  async function saveMovement(){if(operationKind==="outillage"){if(!selectedToolId||!["entree","sortie"].includes(mode))return;setSaving(true);setError("");try{await send({kind:"equipment-movement",assetId:selectedToolId,movementType:mode==="sortie"?"affectation":"retour",personId:mode==="sortie"?personId:null,zoneId:mode==="sortie"?zoneId:null,stockLocationId:mode==="entree"?destinationId:null,note});toast(mode==="sortie"?"Sortie et affectation de l’outil enregistrées":"Retour de l’outil au magasin enregistré");setNote("");await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}return}if(!selected)return;setSaving(true);setError("");try{await send({kind:"stock",movementType:mode,stockItemId:selected.id,quantity:Number(quantity),sourceLocationId:sourceId,destinationLocationId:destinationId,personId:mode==="sortie"?personId:null,zoneId:mode==="sortie"?zoneId:null,note});toast(mode==="inventaire"?"Inventaire et correction enregistrés":"Mouvement enregistré");setQuantity(mode==="inventaire"?"0":"1");setNote("");await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}}
  async function itemSubmit(event:React.FormEvent<HTMLFormElement>,update=false){event.preventDefault();setSaving(true);setError("");const f=new FormData(event.currentTarget);try{const r=await send({kind:update?"stock-item-update":"stock-item-create",stockItemId:selected?.id,reference:f.get("reference"),name:f.get("name"),category:f.get("category"),unit:f.get("unit"),minimumQuantity:Number(f.get("minimumQuantity")),active:update?f.get("active")==="on":true});toast(update?"Article mis à jour":"Article ajouté au catalogue");setShowNewItem(false);setShowEditItem(false);await load();if(r.item?.id)setSelectedId(r.item.id)}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}}
  async function createLocation(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const f=new FormData(event.currentTarget);try{const r=await send({kind:"stock-location-create",name:f.get("name"),code:f.get("code")});toast("Emplacement ajouté");setShowNewLocation(false);await load();if(r.location?.id)setDestinationId(r.location.id)}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}}
  function exportExcel(){fetch("/api/stock/export",{headers:{authorization:`Bearer ${accessToken}`}}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);return r.blob()}).then(blob=>{const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`stock-pilotis-${new Date().toISOString().slice(0,10)}.xls`;a.click();URL.revokeObjectURL(url)}).catch(e=>toast(e instanceof Error?e.message:"Export impossible"))}
  const alerts=items.filter(x=>x.active&&(balances[x.id]||0)<=Number(x.minimum_quantity)).length, today=new Date().toLocaleDateString("en-CA"), todayMoves=movements.filter(x=>x.created_at.slice(0,10)===today).length;
  const selectedMoves=movements.filter(x=>x.stock_item_id===selectedId), weekly=Array.from({length:8},(_,i)=>{const end=new Date();end.setHours(23,59,59,999);end.setDate(end.getDate()-(7-i-1)*7);const start=new Date(end);start.setDate(end.getDate()-6);return{label:start.toLocaleDateString("fr-FR",{day:"2-digit",month:"2-digit"}),value:selectedMoves.filter(m=>m.movement_type==="sortie"&&new Date(m.created_at)>=start&&new Date(m.created_at)<=end).reduce((s,m)=>s+Number(m.quantity),0)}}), maxWeekly=Math.max(1,...weekly.map(x=>x.value));
  const tabs:Mode[]=["sortie","entree","transfert","inventaire"];
  return <div className="content page-content"><div className="page-head"><div><h2>Suivi de stock</h2><p>Stocks par emplacement, transferts, inventaires et historique complet.</p></div><div className="stock-actions"><button onClick={exportExcel}>⇩ Export Excel</button><button onClick={()=>setShowNewLocation(true)}>＋ Emplacement</button><button className="primary" onClick={()=>setMode("entree")}>↓ Nouvelle entrée</button></div></div>
    <div className="stock-summary-grid"><div className="stock-summary-card green"><span>ARTICLES & OUTILS ACTIFS</span><b>{items.filter(x=>x.active).length+tools.filter(x=>x.active).length}</b><small>{tools.filter(x=>x.active).length} outil(s) électroportatif(s)</small></div><div className="stock-summary-card red"><span>ALERTES STOCK</span><b>{alerts}</b><small>au seuil minimum ou en négatif</small></div><div className="stock-summary-card gold"><span>MOUVEMENTS DU JOUR</span><b>{todayMoves+toolMovements.filter(x=>x.created_at.slice(0,10)===today).length}</b><small>articles et électroportatif</small></div></div>
    <div className="stock-layout"><div className="panel stock-table"><div className="panel-title"><div><span>ÉTAT DU STOCK</span><h3>Matériel disponible</h3></div><button disabled={!selected} onClick={()=>setShowDetail(true)}>Voir la fiche</button></div><div className="filters stock-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕ Rechercher…"/><select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">Toutes les familles</option>{availableFamilies.map(x=><option key={x}>{x}</option>)}</select><select value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="active">Articles actifs</option><option value="all">Tous les articles</option><option value="alert">Alertes</option><option value="inactive">Désactivés</option></select></div><div className="stock-table-scroll"><table><thead><tr><th>ARTICLE</th><th>FAMILLE</th><th>DISPONIBLE</th><th>SEUIL</th><th>ÉTAT</th></tr></thead><tbody>{filteredItems.map(item=>{const stock=balances[item.id]||0,alert=stock<=Number(item.minimum_quantity);return <tr key={item.id} onClick={()=>setSelectedId(item.id)} className={selectedId===item.id?"stock-selected":""}><td><b>{item.name}</b><small>{item.reference}</small></td><td>{item.category}</td><td><strong>{stock.toLocaleString("fr-FR")} {item.unit}</strong></td><td>{Number(item.minimum_quantity).toLocaleString("fr-FR")} {item.unit}</td><td><span className={!item.active?"stock-muted":alert?"stock-alert":"stock-ok"}>● {!item.active?"Désactivé":stock<0?"Stock négatif":alert?"Seuil atteint":"Disponible"}</span></td></tr>})}</tbody></table></div></div>
      <div className="panel movement-form"><div className="movement-tabs stock-four-tabs">{tabs.map(tab=><button key={tab} className={mode===tab?"active":""} onClick={()=>{setMode(tab);if(!["entree","sortie"].includes(tab))setOperationKind("article")}}>{movementLabel(tab)}</button>)}</div><div className="movement-body"><span>NOUVELLE OPÉRATION</span><h3>{movementLabel(mode)}</h3>{["entree","sortie"].includes(mode)?<label>Type de matériel<select value={operationKind} onChange={e=>setOperationKind(e.target.value as "article"|"outillage")}><option value="article">Article / consommable</option><option value="outillage">Électroportatif / outillage</option></select></label>:null}{operationKind==="outillage"&&["entree","sortie"].includes(mode)?<label>Outil<select value={selectedToolId} onChange={e=>setSelectedToolId(e.target.value)}>{eligibleTools.map(x=><option value={x.id} key={x.id}>{x.internal_reference} · {x.description}</option>)}</select><small>{eligibleTools.length?(mode==="sortie"?"Seuls les outils disponibles sont proposés":"Seuls les outils affectés sont proposés"):"Aucun outil compatible avec cette opération"}</small></label>:<><label>Article<select value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{items.filter(x=>x.active).map(x=><option value={x.id} key={x.id}>{x.reference} · {x.name}</option>)}</select></label>{mode==="entree"?<button className="text-action add-stock-item" onClick={()=>setShowNewItem(true)}>＋ L’article n’existe pas ? L’ajouter</button>:null}<div className="available">Stock total <b>{currentStock.toLocaleString("fr-FR")} {selected?.unit||""}</b></div></>}
      {operationKind==="article"&&mode!=="entree"?<label>{mode==="inventaire"?"Emplacement inventorié":"Emplacement source"}<select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{locations.filter(x=>x.active).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><small>Disponible ici : {sourceStock.toLocaleString("fr-FR")} {selected?.unit}</small></label>:null}
      {mode==="entree"||mode==="transfert"?<label>Emplacement destination<select value={destinationId} onChange={e=>setDestinationId(e.target.value)}>{locations.filter(x=>x.active).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>:null}
      {operationKind==="article"?<label>{mode==="inventaire"?"Quantité réellement comptée":"Quantité"}<input type="number" min={mode==="inventaire"?"0":"0.01"} step="0.01" value={quantity} onChange={e=>setQuantity(e.target.value)}/><small>{selected?.unit}</small></label>:null}
      {mode==="sortie"?<><label>Personne<select value={personId} onChange={e=>setPersonId(e.target.value)}>{people.map(x=><option value={x.id} key={x.id}>{x.full_name}</option>)}</select></label><label>Zone d’affectation<select value={zoneId} onChange={e=>setZoneId(e.target.value)}>{zones.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></>:null}
      <label>{mode==="inventaire"?"Motif de correction":"Référence / commentaire"}<input value={note} onChange={e=>setNote(e.target.value)} placeholder={mode==="inventaire"?"Obligatoire : inventaire, casse, erreur…":negative?"Justification obligatoire du stock négatif":"BL, bon de sortie, précision…"}/></label>{operationKind==="article"&&negative?<div className="stock-negative-warning">⚠ Cette sortie créera un stock négatif sur cet emplacement.</div>:null}{error?<div className="settings-error">{error}</div>:null}<button className="save" disabled={saving||(operationKind==="outillage"?!eligibleTools.some(tool=>tool.id===selectedToolId):!selected)||(mode==="transfert"&&sourceId===destinationId)||(mode==="inventaire"&&(!note.trim()||Number(quantity)===sourceStock))||(operationKind==="article"&&negative&&!note.trim())} onClick={()=>void saveMovement()}>{saving?"Enregistrement…":"Valider l’opération"}</button></div></div></div>
    <div className="panel movement-history tool-stock-panel"><div className="panel-title"><div><span>ÉLECTROPORTATIF / OUTILLAGE</span><h3>Disponibilité au magasin</h3></div><button onClick={()=>{setMode("sortie");setOperationKind("outillage")}}>Affecter un outil</button></div><div className="stock-table-scroll"><table><thead><tr><th>RÉFÉRENCE</th><th>OUTIL</th><th>STATUT</th><th>EMPLACEMENT / AFFECTATION</th></tr></thead><tbody>{tools.filter(tool=>tool.active).map(tool=><tr key={tool.id}><td><b>{tool.internal_reference}</b></td><td><b>{tool.description}</b><small>{tool.brand||"—"}</small></td><td><span className={`equipment-status ${tool.status}`}>{tool.status==="disponible"?"Disponible":tool.status==="affecte"?"Affecté":tool.status==="maintenance"?"En maintenance":tool.status==="hors_service"?"Hors service":"Restitué"}</span></td><td>{tool.people?.full_name||tool.stock_locations?.name||"—"}</td></tr>)}</tbody></table></div></div>
    <div className="panel movement-history"><div className="panel-title"><div><span>JOURNAL DES MOUVEMENTS</span><h3>Dernières opérations</h3></div></div><div className="stock-table-scroll"><table><thead><tr><th>DATE</th><th>TYPE</th><th>ARTICLE / OUTIL</th><th>QUANTITÉ</th><th>EMPLACEMENT / AFFECTATION</th><th>COMMENTAIRE</th></tr></thead><tbody>{[...movements.map(m=>({date:m.created_at,node:<tr key={`stock-${m.id}`}><td>{new Date(m.created_at).toLocaleString("fr-FR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</td><td><span className={`move-${m.movement_type}`}>{movementLabel(m.movement_type)}</span></td><td><b>{m.stock_items?.name}</b><small>{m.stock_items?.reference}</small></td><td><strong>{m.movement_type==="transfert"?Number(m.quantity):signedQuantity(m).toLocaleString("fr-FR")} {m.stock_items?.unit}</strong></td><td>{m.movement_type==="transfert"?`${locations.find(x=>x.id===m.source_location_id)?.name} → ${locations.find(x=>x.id===m.destination_location_id)?.name}`:m.movement_type==="entree"?locations.find(x=>x.id===m.destination_location_id)?.name:m.movement_type==="sortie"?[locations.find(x=>x.id===m.source_location_id)?.name,m.people?.full_name,m.zones?.name].filter(Boolean).join(" · "):locations.find(x=>x.id===m.source_location_id)?.name}</td><td>{m.note||"—"}</td></tr>})),...toolMovements.map(m=>({date:m.created_at,node:<tr key={`tool-${m.id}`}><td>{new Date(m.created_at).toLocaleString("fr-FR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</td><td><span className={`move-${m.movement_type==="affectation"?"sortie":"entree"}`}>{m.movement_type==="affectation"?"↑ Sortie outil":"↓ Entrée outil"}</span></td><td><b>{m.equipment_assets?.description}</b><small>{m.equipment_assets?.internal_reference}</small></td><td><strong>1 u</strong></td><td>{m.movement_type==="affectation"?[m.people?.full_name,m.zones?.name].filter(Boolean).join(" · "):m.stock_locations?.name||"—"}</td><td>{m.note||"—"}</td></tr>}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,1000).map(row=>row.node)}</tbody></table></div></div>
    {(showNewItem||showEditItem)&&<div className="modal-backdrop"><form className="task-modal" onSubmit={e=>itemSubmit(e,showEditItem)}><div className="modal-title"><div><span>CATALOGUE</span><h3>{showEditItem?"Modifier l’article":"Ajouter un article"}</h3></div><button type="button" onClick={()=>{setShowNewItem(false);setShowEditItem(false)}}>×</button></div><label>Référence<input name="reference" required defaultValue={showEditItem?selected?.reference:""}/></label><label>Désignation<input name="name" required defaultValue={showEditItem?selected?.name:""}/></label><label>Famille<select name="category" defaultValue={showEditItem?selected?.category:families[0]}>{families.map(x=><option key={x}>{x}</option>)}</select></label><label>Unité<select name="unit" defaultValue={showEditItem?selected?.unit:units[0]}>{units.map(x=><option key={x}>{x}</option>)}</select></label><label>Seuil d’alerte<input name="minimumQuantity" type="number" min="0" step="0.01" defaultValue={showEditItem?Number(selected?.minimum_quantity):0}/></label>{showEditItem?<label className="stock-active-check"><input name="active" type="checkbox" defaultChecked={selected?.active}/> Article actif</label>:null}{error?<div className="settings-error">{error}</div>:null}<div className="modal-actions"><button type="button" onClick={()=>{setShowNewItem(false);setShowEditItem(false)}}>Annuler</button><button className="primary" disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</button></div></form></div>}
    {showNewLocation&&<div className="modal-backdrop"><form className="task-modal" onSubmit={createLocation}><div className="modal-title"><div><span>STOCKAGE</span><h3>Nouvel emplacement</h3></div><button type="button" onClick={()=>setShowNewLocation(false)}>×</button></div><label>Nom<input name="name" required placeholder="Ex. Container extérieur"/></label><label>Code<input name="code" placeholder="Ex. CONT-01"/></label>{error?<div className="settings-error">{error}</div>:null}<div className="modal-actions"><button type="button" onClick={()=>setShowNewLocation(false)}>Annuler</button><button className="primary" disabled={saving}>Ajouter</button></div></form></div>}
    {showDetail&&selected&&<div className="modal-backdrop"><div className="task-modal stock-detail"><div className="modal-title"><div><span>FICHE ARTICLE · {selected.reference}</span><h3>{selected.name}</h3></div><button type="button" onClick={()=>setShowDetail(false)}>×</button></div><div className="stock-detail-actions"><span>{selected.category} · seuil {Number(selected.minimum_quantity)} {selected.unit}</span><button onClick={()=>{setShowDetail(false);setShowEditItem(true)}}>Modifier / désactiver</button></div><div className="location-cards">{locations.map(x=><div key={x.id}><span>{x.name}</span><b>{(locationBalances[selected.id]?.[x.id]||0).toLocaleString("fr-FR")} {selected.unit}</b></div>)}</div><h4>Consommation des 8 dernières semaines</h4><div className="stock-chart">{weekly.map((x,i)=><div key={x.label} className="stock-chart-column"><span>{x.value.toLocaleString("fr-FR")}</span><div style={{height:`${Math.max(3,x.value/maxWeekly*100)}%`}}/><small>{i%2===0?x.label:""}</small></div>)}</div><h4>Derniers mouvements</h4><div className="stock-detail-history">{selectedMoves.slice(0,8).map(m=><div key={m.id}><span>{new Date(m.created_at).toLocaleDateString("fr-FR")}</span><b>{movementLabel(m.movement_type)}</b><strong>{m.movement_type==="transfert"?Number(m.quantity):signedQuantity(m)} {selected.unit}</strong></div>)}</div></div></div>}
  </div>
}
